"""Oracle contract tests against a real database.

Set ``LIVEOPS_TEST_ORACLE_DSN`` to an admin connection to a pluggable
database, e.g. ``oracle://system:Your_Password1@localhost:1521/FREEPDB1`` (CI
job ``enterprise-db`` runs ``gvenzl/oracle-free:23-slim``). Each test gets an
owner schema with an ``ASSETS`` table and a separate user that can only
SELECT from it. Skipped when the variable isn't set.
"""

from __future__ import annotations

import asyncio
import os
import uuid
from collections.abc import AsyncIterator
from typing import Any
from urllib.parse import unquote, urlsplit

import pytest

from app.connectors.base import Connector, ConnectorError
from app.connectors.oracle import OracleConnector
from tests.contract.kit import SEED_ROWS, ConnectorContract

ORACLE_DSN = os.environ.get("LIVEOPS_TEST_ORACLE_DSN")
requires_oracle = pytest.mark.skipif(not ORACLE_DSN, reason="LIVEOPS_TEST_ORACLE_DSN not set")


def admin_params() -> dict[str, Any]:
    assert ORACLE_DSN
    u = urlsplit(ORACLE_DSN)
    return {
        "user": unquote(u.username or "system"),
        "password": unquote(u.password or ""),
        "host": u.hostname or "localhost",
        "port": u.port or 1521,
        "service_name": u.path.lstrip("/") or "FREEPDB1",
    }


class OracleDriver:
    def __init__(self) -> None:
        tag = uuid.uuid4().hex[:8].upper()
        self.owner = f"LO_APP_{tag}"
        self.reader = f"LO_RD_{tag}"
        self.password = f"Rd_{uuid.uuid4().hex[:12]}"
        self.dataset = f"{self.owner}.ASSETS"

    def _exec(self, *statements: tuple[str, dict[str, Any] | None]) -> None:
        import oracledb

        with oracledb.connect(**admin_params()) as conn:
            conn.autocommit = True
            cur = conn.cursor()
            for sql, params in statements:
                cur.execute(sql, params or {})

    def setup_sync(self) -> None:
        # Identifiers here are generated by the test (hex), not user input.
        o, r = self.owner, self.reader
        self._exec(
            (f'CREATE USER {o} IDENTIFIED BY "{self.password}" QUOTA UNLIMITED ON USERS', None),
            (
                f'CREATE TABLE {o}.ASSETS ("id" VARCHAR2(20) PRIMARY KEY, "status" VARCHAR2(50), '
                '"zone" VARCHAR2(50), "updated_at" TIMESTAMP DEFAULT SYSTIMESTAMP, '
                '"amount" NUMBER(10,2) DEFAULT 1.50, "notes" CLOB, "blob" BLOB)',
                None,
            ),
            (f'CREATE USER {r} IDENTIFIED BY "{self.password}"', None),
            (f"GRANT CREATE SESSION TO {r}", None),
            (f"GRANT SELECT ON {o}.ASSETS TO {r}", None),
        )
        for row in SEED_ROWS:
            self._insert_sync(row)

    def _insert_sync(self, row: dict[str, Any]) -> None:
        self._exec(
            (
                f'INSERT INTO {self.owner}.ASSETS ("id", "status", "zone", "notes") VALUES (:id, :status, :zone, :n)',
                {"id": row["id"], "status": row["status"], "zone": row["zone"], "n": "long text ✓"},
            )
        )

    def teardown_sync(self) -> None:
        self._exec((f"DROP USER {self.reader} CASCADE", None), (f"DROP USER {self.owner} CASCADE", None))

    async def insert(self, row: dict[str, Any]) -> None:
        await asyncio.to_thread(self._insert_sync, row)

    async def update(self, key: str, changes: dict[str, Any]) -> None:
        await asyncio.to_thread(
            self._exec,
            (
                f'UPDATE {self.owner}.ASSETS SET "status" = :s, "updated_at" = SYSTIMESTAMP WHERE "id" = :k',
                {"s": changes["status"], "k": key},
            ),
        )

    async def delete(self, key: str) -> None:
        await asyncio.to_thread(self._exec, (f'DELETE FROM {self.owner}.ASSETS WHERE "id" = :k', {"k": key}))

    def settings(self) -> dict[str, Any]:
        p = admin_params()
        return {
            "host": p["host"],
            "port": p["port"],
            "service_name": p["service_name"],
            "user": self.reader,
            "encryption": "off",  # the CI image has no TCPS listener; TCPS is unit-tested only
            "schemas": [self.owner],
        }


@requires_oracle
class TestOracleContract(ConnectorContract):
    latency_budget_s = 5.0

    @pytest.fixture
    async def driver(self) -> AsyncIterator[OracleDriver]:
        d = OracleDriver()
        await asyncio.to_thread(d.setup_sync)
        try:
            yield d
        finally:
            await asyncio.to_thread(d.teardown_sync)

    def make_connector(self, driver: OracleDriver) -> Connector:  # type: ignore[override]
        return OracleConnector(driver.settings(), {"password": driver.password})

    def make_bad_connector(self, driver: OracleDriver) -> Connector:  # type: ignore[override]
        return OracleConnector(driver.settings(), {"password": "wrong-password-123"})

    async def test_unknown_table_is_rejected(self, driver: OracleDriver) -> None:
        c = self.make_connector(driver)
        try:
            with pytest.raises(ConnectorError):
                await c.preview(f'{driver.owner}.ASSETS"; DROP TABLE X; --')
        finally:
            await c.close()

    async def test_snapshot_transaction_is_read_only(self, driver: OracleDriver) -> None:
        # Use the admin account (which may write) to prove the READ ONLY transaction itself blocks writes.
        p = admin_params()
        settings = {**driver.settings(), "user": p["user"]}
        c = OracleConnector(settings, {"password": p["password"]})
        try:

            def write_in_read_only_txn(conn: Any) -> None:
                conn.rollback()
                cur = conn.cursor()
                cur.execute("SET TRANSACTION READ ONLY")
                try:
                    cur.execute(f"UPDATE {driver.owner}.ASSETS SET \"status\" = 'x'")
                finally:
                    conn.rollback()

            with pytest.raises(ConnectorError, match="ORA-01456"):
                await c._run(write_in_read_only_txn)
        finally:
            await c.close()

    async def test_clob_and_number_values_are_plain(self, driver: OracleDriver) -> None:
        c = self.make_connector(driver)
        try:
            rows = await c.preview(driver.dataset, limit=1)
        finally:
            await c.close()
        assert rows[0]["notes"] == "long text ✓"
        assert rows[0]["amount"] == 1.5
