"""SQL Server contract tests against a real server.

Set ``LIVEOPS_TEST_MSSQL_DSN`` to an admin connection, e.g.
``mssql://sa:Your_Password1@localhost:1433/master`` (CI job ``enterprise-db``
runs ``mcr.microsoft.com/mssql/server:2022-latest``). Each test gets its own
database with change tracking on, a ``dbo.assets`` table and a login that
can only read it. Skipped when the variable isn't set.
"""

from __future__ import annotations

import asyncio
import os
import uuid
from collections.abc import AsyncIterator
from typing import Any
from urllib.parse import unquote, urlsplit

import pytest

from app.connectors.base import Connector, ConnectorError
from app.connectors.sqlserver import SqlServerConnector
from tests.contract.kit import SEED_ROWS, ConnectorContract

MSSQL_DSN = os.environ.get("LIVEOPS_TEST_MSSQL_DSN")
requires_mssql = pytest.mark.skipif(not MSSQL_DSN, reason="LIVEOPS_TEST_MSSQL_DSN not set")


def admin_params(database: str = "master") -> dict[str, Any]:
    assert MSSQL_DSN
    u = urlsplit(MSSQL_DSN)
    return {
        "server": u.hostname or "localhost",
        "port": str(u.port or 1433),
        "user": unquote(u.username or "sa"),
        "password": unquote(u.password or ""),
        "database": database,
        "autocommit": True,
        "login_timeout": 30,
    }


class MssqlDriver:
    def __init__(self) -> None:
        tag = uuid.uuid4().hex[:8]
        self.db = f"lo_test_{tag}"
        self.login = f"lo_reader_{tag}"
        self.password = f"Rd_{uuid.uuid4().hex[:12]}!9a"
        self.dataset = "dbo.assets"

    def _exec(self, database: str, *statements: tuple[str, tuple[Any, ...] | None]) -> None:
        import pymssql

        with pymssql.connect(**admin_params(database)) as conn:
            cur = conn.cursor()
            for sql, params in statements:
                cur.execute(sql, params)

    def setup_sync(self) -> None:
        # Identifiers here are generated by the test (hex), not user input.
        self._exec(
            "master",
            (f"CREATE DATABASE [{self.db}]", None),
            (
                f"ALTER DATABASE [{self.db}] SET CHANGE_TRACKING = ON (CHANGE_RETENTION = 1 DAYS, AUTO_CLEANUP = ON)",
                None,
            ),
            (f"CREATE LOGIN [{self.login}] WITH PASSWORD = '{self.password}', CHECK_POLICY = OFF", None),
        )
        self._exec(
            self.db,
            (
                "CREATE TABLE dbo.assets (id nvarchar(20) NOT NULL PRIMARY KEY, status nvarchar(50), "
                "zone nvarchar(50), updated_at datetime2 DEFAULT SYSUTCDATETIME(), "
                "amount decimal(10,2) DEFAULT 1.50, blob varbinary(max), uid uniqueidentifier DEFAULT NEWID())",
                None,
            ),
            ("ALTER TABLE dbo.assets ENABLE CHANGE_TRACKING", None),
            *[
                ("INSERT INTO dbo.assets (id, status, zone) VALUES (%s, %s, %s)", (r["id"], r["status"], r["zone"]))
                for r in SEED_ROWS
            ],
            (f"CREATE USER [{self.login}] FOR LOGIN [{self.login}]", None),
            (f"GRANT SELECT ON dbo.assets TO [{self.login}]", None),
            (f"GRANT VIEW CHANGE TRACKING ON dbo.assets TO [{self.login}]", None),
        )

    def teardown_sync(self) -> None:
        self._exec(
            "master",
            (f"ALTER DATABASE [{self.db}] SET SINGLE_USER WITH ROLLBACK IMMEDIATE", None),
            (f"DROP DATABASE [{self.db}]", None),
            (f"DROP LOGIN [{self.login}]", None),
        )

    async def insert(self, row: dict[str, Any]) -> None:
        await asyncio.to_thread(
            self._exec,
            self.db,
            ("INSERT INTO dbo.assets (id, status, zone) VALUES (%s, %s, %s)", (row["id"], row["status"], row["zone"])),
        )

    async def update(self, key: str, changes: dict[str, Any]) -> None:
        await asyncio.to_thread(
            self._exec,
            self.db,
            (
                "UPDATE dbo.assets SET status = %s, updated_at = SYSUTCDATETIME() WHERE id = %s",
                (changes["status"], key),
            ),
        )

    async def delete(self, key: str) -> None:
        await asyncio.to_thread(self._exec, self.db, ("DELETE FROM dbo.assets WHERE id = %s", (key,)))

    def settings(self, **extra: Any) -> dict[str, Any]:
        p = admin_params()
        return {
            "host": p["server"],
            "port": int(p["port"]),
            "database": self.db,
            "user": self.login,
            "encryption": "required",  # the 2022 image serves TLS with a self-signed certificate
            "schemas": ["dbo"],
            **extra,
        }


@pytest.fixture
async def mssql_driver() -> AsyncIterator[MssqlDriver]:
    d = MssqlDriver()
    await asyncio.to_thread(d.setup_sync)
    try:
        yield d
    finally:
        await asyncio.to_thread(d.teardown_sync)


@requires_mssql
class TestSqlServerPollContract(ConnectorContract):
    latency_budget_s = 5.0
    mode = "poll"

    @pytest.fixture
    async def driver(self, mssql_driver: MssqlDriver) -> AsyncIterator[MssqlDriver]:
        yield mssql_driver

    def make_connector(self, driver: MssqlDriver) -> Connector:  # type: ignore[override]
        return SqlServerConnector(driver.settings(mode=self.mode), {"password": driver.password})

    def make_bad_connector(self, driver: MssqlDriver) -> Connector:  # type: ignore[override]
        return SqlServerConnector(driver.settings(mode=self.mode), {"password": "wrong-Password-123"})

    async def test_unknown_table_is_rejected(self, driver: MssqlDriver) -> None:
        c = self.make_connector(driver)
        try:
            with pytest.raises(ConnectorError):
                await c.preview("dbo.assets]; DROP TABLE dbo.assets; --")
        finally:
            await c.close()

    async def test_reader_cannot_write(self, driver: MssqlDriver) -> None:
        c = SqlServerConnector(driver.settings(), {"password": driver.password})
        try:

            def write(conn: Any) -> None:
                conn.cursor().execute("INSERT INTO dbo.assets (id) VALUES ('X1')")

            with pytest.raises(ConnectorError):
                await c._run(write)
        finally:
            await c.close()


@requires_mssql
class TestSqlServerChangeTrackingContract(TestSqlServerPollContract):
    latency_budget_s = 2.0  # CDC target: < 2 s
    mode = "cdc"
    stream_options: dict[str, Any] = {"poll_interval_s": 0.5}
